from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.db.models import Q
from .models import Post, Comment
from .utils import get_country_info, generate_cover_image, analyze_sentiment

def post_list(request):
    query = request.GET.get('q')
    if query:
        posts = Post.objects.filter(
            Q(title__icontains=query) | Q(content__icontains=query) | Q(country__icontains=query)
        ).order_by('-created_at')
    else:
        posts = Post.objects.all().order_by('-created_at')
    
    return render(request, 'blog/post_list.html', {'posts': posts, 'query': query})

def post_detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    comments = post.comments.all().order_by('-created_at')
    country_data = get_country_info(post.country)
    
    # Calculate sentiment counts for display
    pos_count = comments.filter(sentiment_label='Positive').count()
    neu_count = comments.filter(sentiment_label='Neutral').count()
    neg_count = comments.filter(sentiment_label='Negative').count()
    
    context = {
        'post': post,
        'comments': comments,
        'country_data': country_data,
        'pos_count': pos_count,
        'neu_count': neu_count,
        'neg_count': neg_count,
    }
    return render(request, 'blog/post_detail.html', context)

@login_required
def create_post(request):
    if request.method == 'POST':
        title = request.POST.get('title')
        content = request.POST.get('content')
        country = request.POST.get('country', 'India')
        
        if title and content:
            post = Post(title=title, content=content, country=country, author=request.user)
            # AI feature: Generate cover image based on title
            cover_url = generate_cover_image(title)
            post.cover_image_url = cover_url
            post.save()
            messages.success(request, 'Post created successfully! A beautiful cover image was generated by AI.')
            return redirect('post_detail', pk=post.pk)
        else:
            messages.error(request, 'Title and content are required.')
            
    return render(request, 'blog/post_create.html')

@login_required
def add_comment(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == 'POST':
        content = request.POST.get('content')
        if content:
            # AI feature: Analyze sentiment before saving
            sentiment = analyze_sentiment(content)
            Comment.objects.create(post=post, author=request.user, content=content, sentiment_label=sentiment)
            messages.success(request, f'Comment added! The AI labeled it as {sentiment}.')
    return redirect('post_detail', pk=pk)

@login_required
def toggle_like(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.user in post.likes.all():
        post.likes.remove(request.user)
    else:
        post.likes.add(request.user)
    return redirect('post_detail', pk=pk)

def register(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Account created successfully! You can now log in.')
            return redirect('login')
    else:
        form = UserCreationForm()
    return render(request, 'registration/register.html', {'form': form})
